apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zomato-monoapp
  namespace: argocd   # âœ… VERY IMPORTANT
spec:
  project: default

  source:
    repoURL: https://github.com/vignesh1234-vi/K8-manifest-ArgoCd-.git
    targetRevision: main
    path: manifests/zomato-clone

  destination:
    server: https://kubernetes.default.svc
    namespace: zomatoclone

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
